### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by miaooo0000OOOO** [bradmontgomery/word2html#6]
ImportError: cannot import name 'main' from 'word2html.main'

--------------------------
used conda
python 3.9.1

command:
activate
pip install word2html
word2html L:/2_3.docx
-------------------------
(base) L:\>word2html L:/2_3.docx
Traceback (most recent call last):
  File "d:\miniconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda\Scripts\word2html.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'main' from 'word2html.main' (d:\miniconda\lib\site-packages\word2html\main.py)

**Comment by corebots** [comment]
having the same issue :(

**Comment by wxie2017** [comment]
Same issue under Debian GNU/Linux:
```
Traceback (most recent call last):
  File "/usr/local/bin/word2html", line 5, in <module>
    from word2html.main import main
ImportError: cannot import name 'main' from 'word2html.main' (/usr/local/lib/python3.9/dist-packages/word2html/main.py)
```

**Comment by EdungDivinefavour** [comment]
I faced the same issue. Follow the instructions here to properly install pypandoc

https://pypi.org/project/pypandoc/
